PushD "I:\shares\DB_Backup\enterprise\antarctica" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\other\" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHSWDWSQL-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "E:\Backups\sql_backup\" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCCCWMDB-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCCMWMDB-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCCMWMDB-S01" && (forfiles /s /m *.bak /d -14 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCDOWMDB-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCQRWMDB-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCQRWMDB-P02" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCQRWMDB-S01" && (forfiles /s /m *.bak /d -14 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCQRWMDB-S02" && (forfiles /s /m *.bak /d -14 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCTCWMDB-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHCTCWMDB-S01" && (forfiles /s /m *.bak /d -14 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\ASHPRMWMDB-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\Enterprise" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\crimson\HealthPost" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ASHADVWMDB-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ASHENTWMDB-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ASHENTWMDB-P02" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ASHENTWMDB-P03" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ASHENTWMDB-P04" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ASHENTWMDB-P05" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ASHENTWSQL-P02" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ASHENTWSQL-P03" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ATXENTWMDB-P01" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\ATXENTWMDB-P02" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD
PushD "I:\shares\DB_Backup\enterprise\" && (forfiles /s /m *.bak /d -28 /c "cmd /c del @path") & PopD