SELECT TOP 1000 [EventType]
      ,[EventTime]
      ,[SessionXML]
      ,[source_database]
      ,[Obj]
      ,[object_type]
      ,[cpu]
      ,[duration]
      ,[durationMin]
      ,[reads]
      ,[writes]
      ,[StatementText]
      ,[query_plan]
  FROM [DBA_Archive].[dbo].[hist_sql_statement_completed]
  order by [EventTime] desc